source 'https://rubygems.org'

gem 'sinatra'
gem 'rackup'
gem 'sequel', '~> 5.79.0'
gem 'sqlite3'
gem 'rerun'
gem 'dotenv'
gem 'azure-storage-blob'
gem 'mime-types'
gem 'pg'
gem 'concurrent-ruby'
gem 'langchainrb', "~> 0.19.5"
gem 'mail'  # <- Agregado
