source 'https://rubygems.org'

gem 'sinatra'
gem 'rackup'
gem 'sequel', '~> 5.79.0'
gem 'sqlite3'
gem 'rerun'
gem 'dotenv'
gem 'azure-storage-blob'
gem 'mime-types'
gem 'pg'
gem 'concurrent-ruby'
gem 'langchainrb', "~> 0.19.5"
gem 'mail'  # <- Agregado
gem 'rufus-scheduler'
gem 'google-apis-fcm_v1'  # <- Firebase Admin SDK
gem 'googleauth'           # <- Para autenticación
gem 'tzinfo-data'          # <- Necesario para Windows
gem 'jwt'                  # <- JSON Web Tokens
