#@baseUrl = http://localhost:4567
@baseUrl = https://rubysinatra.agreeableisland-1cef4d7f.eastus2.azurecontainerapps.io

# Variables para JWT (actualiza el token después del login)
@token = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo3LCJlbWFpbCI6IjIwMjI0NTU4QGFsb2UudWxpbWEuZWR1LnBlIiwibm9tYnJlIjoiSGVhZHM5MCIsImV4cCI6MTc1MTU3NzcxNSwiaWF0IjoxNzUwOTcyOTE1fQ.me7W-cis4yHa1uq4xj7zd23258dDSiDpqOUQB0J7s24
#############################################
# CREAR RECORDATORIO CON NOTIFICACIÓN FCM [PROTEGIDO]
POST {{baseUrl}}/recordatorios/crear
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "tarea_id": 540,
  "fecha_hora": "2025-06-29T12:59:00",
  "token_fcm": "e8ep0QXLTyq_iX-7cgJ0iy:APA91bFZ29M5oE26x-2HEcXvABJyiHbvMFzevPClUwfYNMgFnd99kRIXP3kQtLQxin_9vAEpa8aXNQj4S1sHYWmlVSTbyQ3cr7sNwhWYSxjZ6FdE8y0lO-I",
  "mensaje": "Renzo listo",
  "activado": true
}

#############################################
# ACTUALIZAR RECORDATORIO [PROTEGIDO]
PUT {{baseUrl}}/recordatorios/actualizar
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 29,
  "tarea_id": 426,
  "fecha_hora": "2025-06-25T01:47:00",
  "token_fcm": "e8ep0QXLTyq_iX-7cgJ0iy:APA91bFZ29M5oE26x-2HEcXvABJyiHbvMFzevPClUwfYNMgFnd99kRIXP3kQtLQxin_9vAEpa8aXNQj4S1sHYWmlVSTbyQ3cr7sNwhWYSxjZ6FdE8y0lO-I",
  "mensaje": "Recordatorio actualizado: No olvides la tarea",
  "activado": false
}

#############################################
# ELIMINAR RECORDATORIO [PROTEGIDO]
DELETE {{baseUrl}}/recordatorios/eliminar/426
Authorization: Bearer {{token}}

#############################################
# OBTENER RECORDATORIOS POR TAREA [PROTEGIDO]
GET {{baseUrl}}/recordatorios/540
Authorization: Bearer {{token}}

#############################################
# DESACTIVAR TODOS LOS RECORDATORIOS DEL USUARIO [PROTEGIDO]
PUT {{baseUrl}}/recordatorios/desactivar-usuario/7
Authorization: Bearer {{token}}

#############################################
# ACTIVAR TODOS LOS RECORDATORIOS DEL USUARIO [PROTEGIDO]
PUT {{baseUrl}}/recordatorios/activar-usuario/7
Authorization: Bearer {{token}}

#############################################
# ACTIVAR RECORDATORIOS DE PRIORIDAD ALTA [PROTEGIDO]
PUT {{baseUrl}}/recordatorios/activar-prioridad-alta/7
Authorization: Bearer {{token}}

#############################################
# OBTENER ESTADO DE RECORDATORIOS DEL USUARIO [PROTEGIDO]
GET {{baseUrl}}/recordatorios/estado-usuario/7
Authorization: Bearer {{token}}

#############################################
# OBTENER recordatorios de tarea
GET {{baseUrl}}/recordatorios/tarea/540
Authorization: Bearer {{token}}

