#@baseUrl = http://localhost:4567
@baseUrl = https://rubysinatra.agreeableisland-1cef4d7f.eastus2.azurecontainerapps.io

# Variables para JWT (actualiza el token después del login)
@token = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo3LCJlbWFpbCI6IjIwMjI0NTU4QGFsb2UudWxpbWEuZWR1LnBlIiwibm9tYnJlIjoiSGVhZHM5MCIsImV4cCI6MTc1MTU3NzcxNSwiaWF0IjoxNzUwOTcyOTE1fQ.me7W-cis4yHa1uq4xj7zd23258dDSiDpqOUQB0J7s24
#############################################
# CREAR TAREA CON ETIQUETAS [PROTEGIDO]
POST {{baseUrl}}/tareas/crear_con_etiquetas
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "usuario_id": 1,
  "lista_id": 1,
  "titulo": "Nueva tarea",
  "descripcion": "Descripción de la tarea",
  "fecha_creacion": "2025-06-24T10:00:00",
  "fecha_vencimiento": "2025-06-30T18:00:00",
  "categoria_id": 1,
  "estado_id": 1,
  "prioridad_id": 1,
  "etiquetas": [1, 2, 3]
}

#############################################
# ACTUALIZAR TAREA CON ETIQUETAS [PROTEGIDO]
PUT {{baseUrl}}/tareas/1/actualizar_con_etiquetas
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "usuario_id": 1,
  "lista_id": 1,
  "titulo": "Tarea actualizada",
  "descripcion": "Descripción actualizada",
  "fecha_creacion": "2025-06-24T10:00:00",
  "fecha_vencimiento": "2025-07-01T18:00:00",
  "categoria_id": 2,
  "estado_id": 2,
  "prioridad_id": 2,
  "etiquetas": [2, 4, 5]
}

#############################################
# ELIMINAR TAREA [PROTEGIDO]
DELETE {{baseUrl}}/tareas/eliminar/1
Authorization: Bearer {{token}}

#############################################
# OBTENER TAREA POR ID [PROTEGIDO]
GET {{baseUrl}}/tareas/obtener/426
Authorization: Bearer {{token}}

#############################################
# OBTENER TODAS LAS TAREAS DE UN USUARIO [PROTEGIDO]
GET {{baseUrl}}/tareas/1
Authorization: Bearer {{token}}

#############################################
# OBTENER ESTADO DE UNA TAREA [PROTEGIDO]
GET {{baseUrl}}/tareas/estado/1
Authorization: Bearer {{token}}

#############################################
# ACTUALIZAR ESTADO DE UNA TAREA [PROTEGIDO]
PUT {{baseUrl}}/tareas/estado/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "estado_id": 2
}
