@baseUrl = http://localhost:4567/

#############################################

POST {{baseUrl}}usuario/validar 
content-type: application/json

{
  "usuario": "Ana García",
  "contrasena": "1234"
}


#############################################
POST {{baseUrl}}usuario/cambiar-contrasenia
Content-Type: application/x-www-form-urlencoded

usuario=renzito&contrasenia=3972re

#############################################
POST {{baseUrl}}usuario/crear-usuario
Content-Type: application/x-www-form-urlencoded

usuario=sapo&contrasenia=3972re

#############################################
GET {{baseUrl}}usuarios/7/datos_completos

#############################################
#############################################
GET {{baseUrl}}tareas/7

#############################################
#############################################
POST {{baseUrl}}tareaetiqueta/85/18
Content-Type: application/json

{}



#############################################
GET {{baseUrl}}adjuntos/1/url
  ?adjunto_id=1

#############################################
GET {{baseUrl}}usuario/7/foto-perfil
  ?usuario_id=7
#############################################

POST {{baseUrl}}usuario/7/token-fcm
Content-Type: application/json

{
  "token_fcm": "1234567890"
}




#############################################
PUT {{baseUrl}}usuario/restablecer-contrasena
Content-Type: application/json

{
  "reset_token": "971bc67c5e5357d5a6dcbe5d40cadfe7",
  "contrasena": "456123"

}


#############################################

DELETE {{baseUrl}}tareas/eliminar/71


#############################################
POST {{baseUrl}}adjuntos/subir
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="prueba.jpg"
Content-Type: image/jpeg

< C:\Users\RENZO\Desktop\Progra Movil\backend\backend\requests\prueba.jpg
--boundary
Content-Disposition: form-data; name="tarea_id"

1
--boundary--

#############################################
curl -X POST {{baseUrl}}adjuntos/subir \
  -F "file=@prueba.jpg" \
  -F "tarea_id=1"

#############################################

POST {{baseUrl}}usuario//foto-perfil
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="foto_perfil.jpg"
Content-Type: image/jpeg

< C:\Users\RENZO\Desktop\Progra Movil\backend\backend\requests\prueba.jpg
--boundary--
#############################################
GET {{baseUrl}}tareas/7

#############################################

PUT {{baseUrl}}tareas/estado/80
Content-Type: application/json

{
  "estado_id": 1
}

#############################################
DELETE  {{baseUrl}}tareaetiqueta/5/125

#############################################
