@baseUrl = https://rubysinatra.agreeableisland-1cef4d7f.eastus2.azurecontainerapps.io
#@baseUrl = http://localhost:4567/
#############################################
# VALIDAR USUARIO
POST {{baseUrl}}/usuario/validar
Content-Type: application/json

{
  "nombre": "renzo455",
  "contrasena": "12345678renzo"
}

#############################################
# CREAR USUARIO
POST {{baseUrl}}/usuario/crear-usuario
Content-Type: application/x-www-form-urlencoded

nombre=Prueba3&contrasena=password123&email=renzoedgar68@gmail.com

#############################################
# ELIMINAR USUARIO
DELETE {{baseUrl}}/usuario/eliminar/12

#############################################
# VERIFICAR SI CORREO EXISTE
GET {{baseUrl}}/usuario/verificar-correo/renzoedgar68@gmail.com

#############################################
# OBTENER USUARIO POR ID
GET {{baseUrl}}/usuario/1

#############################################
# SOLICITAR RECUPERACIÓN DE CONTRASEÑA
POST {{baseUrl}}/usuario/solicitar-recuperacion
Content-Type: application/json

{
  "email": "ana@example.com"
}

#############################################
# RESTABLECER CONTRASEÑA CON TOKEN
PUT {{baseUrl}}/usuario/restablecer-contrasena
Content-Type: application/json

{
  "reset_token": "1cee00f753830752cf82826cdc2e5572",
  "contrasena": "nueva_password123"
}

#############################################
# VERIFICAR TOKEN DE RECUPERACIÓN
GET {{baseUrl}}/usuario/verificar-token/abc123def456

#############################################
# SUBIR FOTO DE PERFIL
POST {{baseUrl}}/usuario/1/foto-perfil
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="prueba.jpg"
Content-Type: image/jpeg

< prueba.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

#############################################
# OBTENER URL DE FOTO DE PERFIL
GET {{baseUrl}}/usuario/1/foto-perfil

#############################################
# ELIMINAR FOTO DE PERFIL
DELETE {{baseUrl}}/usuario/1/foto-perfil

#############################################
# ACTUALIZAR NOMBRE DE USUARIO
PUT {{baseUrl}}/usuario/actualizar-nombre/1
Content-Type: application/json

{
  "nombre": "nuevo_nombre_usuario"
}

#############################################
# ACTUALIZAR CORREO DE USUARIO
PUT {{baseUrl}}/usuario/actualizar-correo/1
Content-Type: application/json

{
  "email": "nuevo_email@ejemplo.com"
}


#############################################
# ASIGNAR TOKEN FCM A USUARIO
POST {{baseUrl}}/usuario/1/token-fcm
Content-Type: application/json

{
  "token_fcm": "token_fcm_del_dispositivo_ejemplo"
}

#############################################
# OBTENER DATOS COMPLETOS DE USUARIO
GET {{baseUrl}}/usuarios/1/datos_completos

#############################################